Add REAL
lukesampson/scoop-extras pull request #4498
Opened 2020-07-31 23:19 UTC by ghost-420

Note: "bin" and "shortcuts" done nothing while I've tested.

2020-08-01 10:20 UTC, Ash258 commented on bucket/real.json
> +    "description": "Reduce audio latency on Windows 10",
```suggestion
    "description": "Reduce audio latency on Windows 10.",
```

2020-08-01 10:22 UTC, Ash258 commented on bucket/real.json
> +    }
```suggestion
    "suggest": {
        "vcredist": "vcredist2017"
    },
    "architecture": {
        "64bit": {
            "url": "https://github.com/miniant-git/REAL/releases/download/updater-v2/REAL.exe",
            "hash": "d9767fd0e29a9fcdd274282de81c82d7b8fb16f268fa2a7cec50c01d0dd3c4ad"
        }
    },
    "pre_install": "if ([Environment]::OSVersion.Version.Major -lt 10) { throw 'Windows 10 is required' }",
    "bin": "REAL.exe",
    "shortcuts": [
        [
            "REAL.exe",
            "Reduce Audio Latency",
            "--tray"
        ]
    ],
    "checkver": {
        "github": "https://github.com/miniant-git/REAL",
        "regex": ">REAL\\s+v([\\d.]+)</"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/miniant-git/REAL/releases/download/updater-v2/REAL.exe"
            }
        }
    }
```

2020-08-06 06:52 UTC, ghost-420 commented
Works fully as intended after applying the suggested changes.

2020-08-09 14:29 UTC, Ash258 commented on bucket/real.json
> +    ],
```suggestion
```

2020-08-19 02:39 UTC, ghost-420 commented on bucket/real.json
> +    ],
Why?

2020-08-19 05:55 UTC, Ash258 requested changes

2020-08-19 05:55 UTC, Ash258 commented on bucket/real.json
> +    ],
```suggestion
```

2020-08-21 08:02 UTC, Ash258 commented
/verify

2020-08-23 18:29 UTC, merged