remove-empty-directories: Add version 2.2
lukesampson/scoop-extras pull request #4604
Opened 2020-08-18 20:59 UTC by kunago

2020-08-19 06:45 UTC, Ash258 requested changes
How do you enable portable mode??

2020-08-19 06:45 UTC, Ash258 commented on bucket/remove-empty-directories.json
> +      ["RED2.exe", "remove-empty-directories"]
```suggestion
        "RED2.exe",
        [
            "RED2.exe",
            "remove-empty-directories"
        ]
```

2020-08-19 06:45 UTC, Ash258 commented on bucket/remove-empty-directories.json
> +      ]
```suggestion
        [
            "RED2.exe",
            "Remove Empty Directories"
        ]
```

2020-08-19 06:45 UTC, Ash258 commented on bucket/remove-empty-directories.json
> +    "hash": "f0114240d4cfc1f5bf81bdd8f38f6f161f15bd98e8ce2332123448f96ce7c423",
```suggestion
    "hash": "sha1:00124046586afd9ca21957363b00da3c2e72cb9b",
```

2020-08-19 06:45 UTC, Ash258 commented on bucket/remove-empty-directories.json
> +    "homepage": "https://www.jonasjohn.de/red.htm",
![image](https://user-images.githubusercontent.com/13260377/90601348-56a4c780-e1f8-11ea-8e87-222c994d2659.png)


```suggestion
    "description": "A tool to batch delete empty folders",
    "homepage": "https://www.jonasjohn.de/red.htm",
    "license": "LGPL-3.0-or-later",
```

2020-08-19 06:53 UTC, kunago commented on bucket/remove-empty-directories.json
> +    "hash": "f0114240d4cfc1f5bf81bdd8f38f6f161f15bd98e8ce2332123448f96ce7c423",
Is SHA1 a standard to use?

2020-08-19 06:54 UTC, Ash258 commented on bucket/remove-empty-directories.json
> +    "hash": "f0114240d4cfc1f5bf81bdd8f38f6f161f15bd98e8ce2332123448f96ce7c423",
It is automatic for sourceforge URLS...

2020-08-19 06:57 UTC, kunago commented
Sorry, don't get this. I don't see anything to enable the portable mode. There is a portable version to download.

2020-08-19 07:16 UTC, Ash258 commented
Yes it is. But the configuration file is stored in APPDATA.

How do you enable the portable mode?

2020-08-20 07:11 UTC, kunago commented
You can't, true. I looked at the code and obviously did not notice the config file in the APPDATA folder.

2020-08-20 07:11 UTC, closed without merging