clumsy: Add version 0.2
lukesampson/scoop-extras pull request #4611
Opened 2020-08-20 08:12 UTC by sebmaynard

clumsy makes your network condition on Windows significantly worse, but in a managed and interactive manner. 

Fantastic for network testing games or other software

2020-08-20 08:50 UTC, Ash258 requested changes

2020-08-20 08:50 UTC, Ash258 commented on bucket/clumsy.json
> +}
```suggestion
{
    "version": "0.2",
    "description": "Broken network simulator",
    "homepage": "https://jagt.github.io/clumsy/",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "https://github.com/jagt/clumsy/releases/download/0.2/clumsy-0.2-win64.zip",
            "hash": "19042ae5e28412a8eb2dc67f4bc3b606ef04cb6f46ef72563f25e41b2bc67609"
        },
        "32bit": {
            "url": "https://github.com/jagt/clumsy/releases/download/0.2/clumsy-0.2-win32.zip",
            "hash": "ad79829832996024981d0161d4862cf28f0d7839a6c6b1b81b55d6335a1b4df9"
        }
    },
    "bin": "clumsy.exe",
    "shortcuts": [
        [
            "clumsy.exe",
            "clumsy"
        ]
    ],
    "persist": "config.txt",
    "checkver": {
        "github": "https://github.com/jagt/clumsy"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/jagt/clumsy/releases/download/$version/clumsy-$version-win64.zip"
            },
            "32bit": {
                "url": "https://github.com/jagt/clumsy/releases/download/$version/clumsy-$version-win32.zip"
            }
        }
    }
}

```

2020-08-20 09:11 UTC, sebmaynard commented
Thank you for the suggestions, still learning how these things should work!

2020-08-20 09:18 UTC, Ash258 requested changes

2020-08-20 09:18 UTC, Ash258 commented on bucket/clumsy.json
> +        }
```suggestion
        },
        "hash": {
            "url": "https://jagt.github.io/clumsy/download.html",
            "regex": "$basename</a>\\s*\\(MD5:$md5\\)"
        }
```

2020-08-20 09:18 UTC, Ash258 commented on bucket/clumsy.json
> +            "hash": "ad79829832996024981d0161d4862cf28f0d7839a6c6b1b81b55d6335a1b4df9"
```suggestion
            "hash": "md5:9aab0d257661a4f75831a7186254725b"
```

2020-08-20 09:18 UTC, Ash258 commented on bucket/clumsy.json
> +            "hash": "19042ae5e28412a8eb2dc67f4bc3b606ef04cb6f46ef72563f25e41b2bc67609"
```suggestion
            "hash": "md5:c5117edad320930d14d18c1cac2a4ccd"
```

2020-08-21 08:06 UTC, Ash258 commented
/verify

2020-08-23 18:30 UTC, merged