gcfscape: Add version 1.8.6
lukesampson/scoop-extras pull request #4693
Opened 2020-09-02 15:17 UTC by ghost-420

2020-09-02 17:38 UTC, Ash258 requested changes

2020-09-02 17:38 UTC, Ash258 commented on bucket/gcfscape.json
> +    "homepage": "http://nemesis.thewavelength.net/index.php?c=169",
![image](https://user-images.githubusercontent.com/13260377/92016827-2cecb400-ed53-11ea-8e02-01e8b5edba25.png)

2020-09-02 17:38 UTC, Ash258 commented on bucket/gcfscape.json
> +    "license": "Freeware",
```suggestion
    "license": "Freeware",
    "suggest": {
        "vcredist": "extras/vcredist2008"
    },
```

2020-09-02 17:38 UTC, Ash258 commented on bucket/gcfscape.json
> +    "hash": "5b61408a83b61afc9c775534cf02749edfde8e570bf17604bc191f6dc57055b0",
```suggestion
    "hash": "5b61408a83b61afc9c775534cf02749edfde8e570bf17604bc191f6dc57055b0",
    "architecture": {
        "64bit": {
            "extract_dir": "x64"
        },
        "32bit": {
            "extract_dir": "x86"
        }
    },
```

2020-09-02 17:38 UTC, Ash258 commented on bucket/gcfscape.json
> +    }
```suggestion
    ]
```

2020-09-02 17:38 UTC, Ash258 commented on bucket/gcfscape.json
> +    },
```suggestion
```

2020-09-02 17:39 UTC, Ash258 requested changes

2020-09-02 17:39 UTC, Ash258 commented on bucket/gcfscape.json
> +    "description": "A archive viewer and extractor for BSP, GCF, NCF, PAK, SGA, VPK, WAD, and XZP files.",
```suggestion
    "description": "An archive viewer and extractor for BSP, GCF, NCF, PAK, SGA, VPK, WAD, and XZP files",
```

2020-09-02 19:23 UTC, ghost-420 commented
![csrss_thIpQjicka](https://user-images.githubusercontent.com/29991266/92027168-0e68c780-ed17-11ea-9fd9-c7e081d14889.png)
![EmuHawk_TSK1SpPLdP](https://user-images.githubusercontent.com/29991266/92027171-0f99f480-ed17-11ea-9ce6-3c78b8bffc03.png)
What makes EmuHawk exempt?

2020-09-02 19:24 UTC, ghost-420 commented
![alacritty_h51ARdXWXi](https://user-images.githubusercontent.com/29991266/92027340-3bb57580-ed17-11ea-98a8-6def4f55d038.png)

2020-09-02 19:36 UTC, Ash258 commented
How is EmuHawk even relevant to this conversation??

PR will be closed unless you provide valid, English homepage

2020-09-02 19:43 UTC, ghost-420 commented
> How is EmuHawk even relevant to this conversation??

Nevermind, I thought it was removed, not moved up.

2020-09-07 16:45 UTC, Ash258 commented
/verify

2020-09-07 16:46 UTC, Ash258 approved these changes

2020-09-08 05:47 UTC, merged