android-studio: suggest android-clt
lukesampson/scoop-extras pull request #4738
Opened 2020-09-11 08:45 UTC by kidonng

Now that ScoopInstaller/Main#1362 has been merged, we can suggest the new SDK instead.

2020-09-11 08:48 UTC, Ash258 requested changes

2020-09-11 08:48 UTC, Ash258 commented on bucket/android-studio.json
> +        "SDK": "android-clt"
Add both

2020-09-12 09:42 UTC, merged

2020-10-22 23:25 UTC, pratikpc commented
@kidonng should Flutter also depend on CLT instead of the SDK?

2020-10-23 02:03 UTC, kidonng commented
@pratikpc I think so, you are welcome to try submit a PR