Create symphytum.json
lukesampson/scoop-extras pull request #4742
Opened 2020-09-12 02:00 UTC by jeremy886

2020-09-12 09:42 UTC, Ash258 requested changes

2020-09-12 09:42 UTC, Ash258 commented on bucket/symphytum.json
> +        "url": "https://github.com/giowck/symphytum/releases/download/$version/Symphytum-windows-portable.zip"
```suggestion
    "version": "2.6",
    "description": "Personal database software to manage and organize data in an easy and intuitive way.",
    "homepage": "https://github.com/giowck/symphytum",
    "license": "BSD-2-Clause",
    "url": "https://github.com/giowck/symphytum/releases/download/v2.6/Symphytum-windows-portable.zip",
    "hash": "0a5ca2264c0edf32efd388a6b60a186c6a13bd1e81fa837416abc8a9cb6260ae",
    "extract_dir": "Symphytum portable",
    "pre_install": [
        "if (!(Test-Path \"$persist_dir\\portable_data\")) {",
        "    ensure \"$dir\\portable_data\" | Out-Null",
        "    Set-Content \"$dir\\portable_data\\settings.ini\" '[symphytum]', 'userConfirmUpdatesCheck=true', 'checkUpdates=false' -Encoding Ascii",
        "}"
    ],
    "shortcuts": [
        [
            "symphytum.exe",
            "Symphytum"
        ]
    ],
    "persist": "portable_data",
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/giowck/symphytum/releases/download/v$version/Symphytum-windows-portable.zip"
```

2020-09-21 04:12 UTC, jeremy886 reviewed
thanks

2020-09-21 13:27 UTC, Ash258 commented
/verify

2020-09-21 13:29 UTC, Ash258 approved these changes

2020-09-27 13:57 UTC, merged