jami: Update to version 202008121023
lukesampson/scoop-extras pull request #4774
Opened 2020-09-17 12:46 UTC by linsui

2020-09-17 12:48 UTC, Ash258 requested changes
Disable checkver

![image](https://user-images.githubusercontent.com/13260377/93472390-d8ba0600-f8f4-11ea-9061-002a2da32cbf.png)

2020-09-17 12:51 UTC, linsui commented
I changed the checkver.

2020-09-18 07:33 UTC, Ash258 requested changes

2020-09-18 07:33 UTC, Ash258 commented on bucket/jami.json
> +        "regex": "jami_x86_64-(\\d+).msi"
```suggestion
        "regex": "jami_x86_64-(\\d+)\\.msi"
```

2020-09-18 07:55 UTC, Ash258 commented
/verify

2020-09-18 07:57 UTC, merged