Add Cyberduck 7.6.1.33485
lukesampson/scoop-extras pull request #4790
Opened 2020-09-20 10:27 UTC by integzz

2020-09-20 10:52 UTC, integzz commented
Sorry, I am not sure what you're pointing out here? Do you mean that I have to add the `persist` path instead of storing the profiles in `%APPDATA%\\Cyberduck\\Profiles` , which is mentioned in `notes`?

2020-09-20 12:04 UTC, Ash258 requested changes

2020-09-21 13:34 UTC, Ash258 commented
/verify

2020-09-21 13:36 UTC, Ash258 approved these changes

2020-09-27 13:57 UTC, merged