ccextractor: Add version 0.88
lukesampson/scoop-extras pull request #4946
Opened 2020-10-20 15:38 UTC by spongbros

https://github.com/ScoopInstaller/Main/pull/1509#issuecomment-712931892

2020-10-20 16:01 UTC, Ash258 requested changes
- Why there are two command line executables?
- Where did you get information that the final product license is GPL2?
- Where are all configurations saved?

2020-10-20 16:27 UTC, spongbros commented
- `ccextractorwinfull.exe` supports OCR and requires `vcredist2013`; `ccextractorwin.exe` lacks OCR functionality and has no external dependencies.
- The license is listed as GNU General Public License version 2.0 (GPL-2.0) in https://github.com/CCExtractor/ccextractor/blob/master/README.md and in https://github.com/CCExtractor/ccextractor/blob/master/docs/README.TXT.
- Running `CCExtractorGUI.exe` and saving settings created the file `"C:\Users\Redacted\AppData\Local\Microsoft\CCExtractorGUI.exe_Url_faxqj13ss0g1iqowz533cntb2rmidqdg\0.0.0.88\user.config"`.

2020-10-22 17:17 UTC, Ash258 commented
/verify

2020-10-22 17:19 UTC, Ash258 approved these changes

2020-10-22 18:27 UTC, merged