musescore: Update to version 3.5.2.311459983
lukesampson/scoop-extras pull request #4981
Opened 2020-10-26 15:04 UTC by colkey

fix #4941

2020-10-26 15:43 UTC, Ash258 requested changes

2020-10-26 15:43 UTC, Ash258 commented on bucket/musescore.json
> +                "url": "https://github.com/musescore/MuseScore/releases/download/$matchUrl.msi",
```suggestion
                "url": "https://github.com/musescore/MuseScore/releases/download/v$matchHead/MuseScore-$version-x86.msi",
```

2020-10-26 15:43 UTC, Ash258 commented on bucket/musescore.json
> +                "url": "https://github.com/musescore/MuseScore/releases/download/$matchUrl_64.msi",
```suggestion
                "url": "https://github.com/musescore/MuseScore/releases/download/v$matchHead/MuseScore-$version-x86_64.msi",
```

2020-10-26 15:43 UTC, Ash258 commented on bucket/musescore.json
> +        "regex": "download/(?<url>[^\"]+)_64.msi\"\\s+sparkle:version=\"(?<version>[\\d.]+)\""
```suggestion
        "regex": "sparkle:version=\"([\\d.]+)\""
```

2020-10-27 11:26 UTC, colkey commented
Thanks for reviewing.
Applied all requests.

2020-10-28 08:03 UTC, igitur approved these changes

2020-10-28 18:07 UTC, Ash258 commented
/verify

2020-10-28 18:09 UTC, merged