amp_winoff: Add version 5.0.1
lukesampson/scoop-extras pull request #4983
Opened 2020-10-27 09:52 UTC by wenmin92

2020-10-28 15:23 UTC, rasa commented
/verify

2020-10-28 18:19 UTC, Ash258 requested changes

2020-10-28 18:19 UTC, Ash258 commented on bucket/amp-winoff.json
> +    "description": "An utility for scheduling the shutdown of Windows computers, with several shutdown conditions and fully configurable.",
```suggestion
    "description": "Fully configurable utility for scheduling the shutdown of Windows computers",
```

2020-10-28 18:19 UTC, Ash258 commented on bucket/amp-winoff.json
> +    }
Latest version was 2010

```suggestion
    ]
```

2020-10-29 01:42 UTC, wenmin92 commented on bucket/amp-winoff.json
> +    }
Thanks!

2020-10-30 08:09 UTC, Ash258 approved these changes

2020-10-30 14:05 UTC, merged