xmousebuttoncontrol: Update to version 2.19.2
lukesampson/scoop-extras pull request #5132
Opened 2020-11-16 21:26 UTC by earnestma

2020-11-16 21:30 UTC, earnestma commented
e9544b4 Chatty is something I am working on adding and forgot to move out of; it's not part of this PR though. sorry for the confusion.

2020-11-17 09:08 UTC, Ash258 requested changes
L34:

```diff
-        "regex": "Version ([\\d.]+)\\s+\\(\\d"
+        "regex": "Version ([\\d.]+)</"
```

2020-11-17 09:08 UTC, Ash258 commented on bucket/xmousebuttoncontrol.json
> +    "hash": "E8AE30AC6929A737685E16080B6B14CE65FC2C5B9F01709C3AE5EAF1F82E7D35",
```suggestion
    "hash": "e8ae30ac6929a737685e16080b6b14ce65fc2c5b9f01709c3ae5eaf1f82e7d35",
```

2020-11-17 13:54 UTC, Ash258 commented
As in other PR. Next PR which will not be opened with write access to the collaborators will be immediately closed.

2020-11-17 13:55 UTC, merged