chatty: Add version version 0.13
lukesampson/scoop-extras pull request #5133
Opened 2020-11-16 21:55 UTC by earnestma

2020-11-17 09:02 UTC, Ash258 requested changes

2020-11-17 09:02 UTC, Ash258 commented on bucket/chatty.json
> +    ],
```suggestion
    ],
    "persist": [
        "app\\portable_settings",
        "app\\Chatty.cfg"
    ],
```

2020-11-17 09:02 UTC, Ash258 commented on bucket/chatty.json
> +    "bin": "Chatty.exe",
```suggestion
    "pre_install": [
        "if (!(Test-Path \"$persist_dir\\app\\Chatty.cfg\")) {",
        "    ensure \"$dir\\app\\portable_settings\" | Out-Null",
        "    $cfg = \"$dir\\app\\Chatty.cfg\"",
        "    (Get-Content $cfg) -replace '(\\[ArgOptions\\])', \"`$1`r`n-portable\" | Set-Content $cfg -Encoding Ascii -Force",
        "    Set-Content \"$dir\\app\\portable_settings\\settings\" '{ \"checkNewVersion\": false }' -Encoding Ascii",
        "}"
    ],
    "bin": "Chatty.exe",
```

2020-11-17 13:53 UTC, Ash258 commented
Your contributions will not be accepted if you will not follow github flow.

Next time you will commit changes not from UI using suggestions and without giving credits to review your all your PRs will be closed.

2020-11-17 13:58 UTC, Ash258 requested changes

2020-11-17 13:58 UTC, Ash258 commented on bucket/chatty.json
> +    "homepage": "https://chatty.github.io/",
```suggestion
    "description": "Twitch Chat Client",
    "homepage": "https://chatty.github.io",
```

2020-11-17 13:58 UTC, Ash258 commented on bucket/chatty.json
> +            "url": "https://tduva.com/chatty/checksums/v$version/Chatty_$version_win_standalone.zip.sha256"
Slightly better

```suggestion
            "url": "https://tduva.com/chatty/checksums/v$version/$basename.sha256"
```

2020-11-17 14:04 UTC, earnestma commented
Very sorry about that. How should I allow your write access to PRs?

2020-11-17 14:30 UTC, earnestma commented
nvm, it looks like [that option is only available for user forks](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) (I usually fork to an org). Next time I'll use a personal fork instead

2020-11-19 22:08 UTC, Ash258 commented
/verify

2020-11-19 22:09 UTC, Ash258 approved these changes

2020-11-22 19:00 UTC, merged