WIP: adding cfssl
lukesampson/scoop-extras pull request #5144
Opened 2020-11-18 16:56 UTC by kennedy

Resolves #5104

The `cfssl` is really a suite of utilities including `cfssl-bundle`, `cfssl-certinfo`, `cfssl-newkey`, `cfssl-scan`, `cfssljson`, `mkbundle`, `multirootca`. I've include them all in the `url`, `bin`, and `hash`

However, `autoupdate` only recognizes and updates the hash for the base app `cfssl`, but not the other utilities, even thought they are in the `autoupdate.hash` file

Do I:

1. Make individual app manifest for each utility, and have them listed as `depends/suggest` on `cfssl`?
2. Is there a special configuration I am missing for this use case?

2020-11-18 16:58 UTC, kennedy commented
/verify

2020-11-18 17:05 UTC, kennedy commented
/verify

2020-11-18 17:12 UTC, Ash258 reviewed
Remove autoupdate

2020-11-18 17:15 UTC, Ash258 requested changes

2020-11-18 17:15 UTC, Ash258 commented on bucket/cfssl.json
> +    "description": "CloudFlare's PKI/TLS toolkit",
Completely saying-nothing description

2020-11-18 17:15 UTC, Ash258 commented on bucket/cfssl.json
> +    "homepage": "https://github.com/cloudflare/cfssl",
Use url from repository description

2020-11-18 17:17 UTC, Ash258 requested changes
This has to fail on installation immediatelly on first shim.

2020-11-18 17:17 UTC, Ash258 commented on bucket/cfssl.json
> +        "https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl_1.5.0_windows_amd64.exe",
This is obviously 64bit only

2020-11-18 17:27 UTC, kennedy commented
> Remove autoupdate

Is that the usual solution for situations like this?

2020-11-18 17:27 UTC, kennedy commented on bucket/cfssl.json
> +    "description": "CloudFlare's PKI/TLS toolkit",
I will add the official des

2020-11-18 19:16 UTC, kennedy commented on bucket/cfssl.json
> +        "https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl_1.5.0_windows_amd64.exe",
ill add the arch section

2020-11-18 19:16 UTC, kennedy commented
/verify

2020-11-18 19:18 UTC, Ash258 commented
Stop wasting github actions time on each line you change. Completely nonsense. Setup local environment instead

2020-11-18 19:30 UTC, Ash258 requested changes

2020-11-18 19:30 UTC, Ash258 commented on bucket/cfssl.json
> +    "homepage": "https://cfssl.org/",
```suggestion
    "description": "Command line tool and an HTTP API server for signing, verifying, and bundling TLS certificates.",
    "homepage": "https://cfssl.org",
```

2020-11-18 19:30 UTC, Ash258 commented on bucket/cfssl.json
> +                "multirootca.exe"
```suggestion
```

2020-11-18 19:30 UTC, Ash258 commented on bucket/cfssl.json
> +    "checkver": {
```suggestion
    "bin": [
        "cfssl.exe",
        "cfssl-bundle.exe",
        "cfssl-certinfo.exe",
        "cfssl-newkey.exe",
        "cfssl-scan.exe",
        "cfssljson.exe",
        "mkbundle.exe",
        "multirootca.exe"
    ],
    "checkver": {
```

2020-11-18 19:30 UTC, Ash258 commented on bucket/cfssl.json
> +            ],
```suggestion
            "url": [
                "https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl_1.5.0_windows_amd64.exe#/cfssl.exe",
                "https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssljson_1.5.0_windows_amd64.exe#/cfssljson.exe",
                "https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl-bundle_1.5.0_windows_amd64.exe#/cfssl-bundle.exe",
                "https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl-certinfo_1.5.0_windows_amd64.exe#/cfssl-certinfo.exe",
                "https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl-newkey_1.5.0_windows_amd64.exe#/cfssl-newkey.exe",
                "https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl-scan_1.5.0_windows_amd64.exe#/cfssl-scan.exe",
                "https://github.com/cloudflare/cfssl/releases/download/v1.5.0/mkbundle_1.5.0_windows_amd64.exe#/mkbundle.exe",
                "https://github.com/cloudflare/cfssl/releases/download/v1.5.0/multirootca_1.5.0_windows_amd64.exe#/multirootca.exe"
            ],
            "hash": [
                "fce669f20d9f25dce20e4a39742613434e16c444ef5745aa91e546223031dbd5",
                "6fd4776e044489f1858ed33e7cfe09728396f1d01e5d5d5934b78c7ab5cddab9",
                "3ecc18c7e168d611d63f84d63778a8c629b4223718d02094e4e8124cfc18440a",
                "17282aba7a47205be7b937b541af1f33f75654afc66d3a54081a23a20273ad14",
                "39cb0f739fec07ae8b16d3fd7e07929656748a1eb5b12e0632d1864282eb5d76",
                "0e7371833942508e939beb051c09aa4112f3e4743460d549d23f8aace5ab0239",
                "aa3c8c84ac3c0e8ff69d798a01ea25fdd15934b92f7979c9c1cebca845446f7e",
                "cea263e6e58aa20d924bc5f04aa67882a5a1660a2d05d473a192efdf8648b066"
            ]
```

2020-11-18 22:25 UTC, kennedy reviewed
I will add these changes

2020-11-19 21:55 UTC, Ash258 requested changes

2020-11-19 21:55 UTC, Ash258 commented on bucket/cfssl.json
> +                "https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl_1.5.0_windows_amd64.exe#/cfssl.exe",
```suggestion
                "https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl_1.5.0_windows_amd64.exe#/cfssl.exe",
                "https://github.com/cloudflare/cfssl/releases/download/v1.5.0/cfssl-bundle_1.5.0_windows_amd64.exe#/cfssl-bundle.exe",
```

2020-11-19 21:55 UTC, Ash258 commented on bucket/cfssl.json
> +                "fce669f20d9f25dce20e4a39742613434e16c444ef5745aa91e546223031dbd5",
```suggestion
                "fce669f20d9f25dce20e4a39742613434e16c444ef5745aa91e546223031dbd5",
                "3ecc18c7e168d611d63f84d63778a8c629b4223718d02094e4e8124cfc18440a",
```

2020-11-21 16:15 UTC, Ash258 commented
/verify

2020-11-21 16:16 UTC, Ash258 approved these changes

2020-11-22 18:59 UTC, merged