alacritty: Update to version 0.6.0
lukesampson/scoop-extras pull request #5179
Opened 2020-11-25 02:49 UTC by earnestma

- Alacritty has moved to an organization, updated URL
- File has also changed from zip to one exe

2020-11-25 07:01 UTC, Ash258 requested changes
Do not work

![A](https://i.imgur.com/G0Bb2cs.png)

2020-11-25 07:01 UTC, Ash258 commented on bucket/alacritty.json
> +        "url": "https://github.com/alacritty/alacritty/releases/download/v$version/Alacritty-v$version-portable.exe"
```suggestion
        "url": "https://github.com/alacritty/alacritty/releases/download/v$version/Alacritty-v$version-portable.exe#/alacritty.exe"
```

2020-11-25 07:01 UTC, Ash258 commented on bucket/alacritty.json
> +    "url": "https://github.com/alacritty/alacritty/releases/download/v0.6.0/Alacritty-v0.6.0-portable.exe",
```suggestion
    "url": "https://github.com/alacritty/alacritty/releases/download/v0.6.0/Alacritty-v0.6.0-portable.exe#/alacritty.exe",
```

2020-11-25 21:43 UTC, meltinglava commented
Can confirm this works for me

2020-11-30 15:09 UTC, meltinglava commented
Bump @Ash258

2020-11-30 15:14 UTC, Ash258 commented
I hav eno idea, why do you spam me with nonsensual notification, when you have clear comment, which was not answered and whole thread has label waiting-feedback

![image](https://user-images.githubusercontent.com/13260377/100627288-1ee50a00-3327-11eb-8131-ad72994e1050.png)

2020-11-30 15:43 UTC, earnestma commented
![image](https://user-images.githubusercontent.com/51169564/100630566-b848f780-32f8-11eb-858a-4a16aa748886.png)

works fine for me now

2020-11-30 15:45 UTC, Ash258 commented
Which means, that there is some dependency required. Which is not specified in the manifest. I am not gonna merge until it is solved...

2020-11-30 16:11 UTC, earnestma commented
hmm, https://github.com/alacritty/alacritty#installation specifies no dependencies.

It may be an alacritty issue itself per https://github.com/alacritty/alacritty/issues/2740

Are you using remote desktop/ what GPU do you have, and does this happen on 0.5.0?

2020-12-05 14:08 UTC, equinox commented
So what happens about this now?

I too can confirm it works fine for me.

2020-12-18 05:31 UTC, dotjairo commented
@Ash258  what version of Windows did you run this on? Any other details of the environment would be helpful I think, for example, was this on a physical machine or a VM? If VM, which hypervisor.  Thanks!

2020-12-18 18:07 UTC, rasa commented
> @Ash258 what version of Windows did you run this on? Any other details of the environment would be helpful I think, for example, was this on a physical machine or a VM? If VM, which hypervisor? Thanks!

My guess in @Ash258 is [using](https://github.com/Ash258/Scoop-Ash258/blob/5409f1b648a9493182eb56ccf9d68bbf5689834c/Vagrantfile#L5) which was Windows 10 2004 (until 6 hours ago) and is now Windows 10 2009. See [here](https://app.vagrantup.com/gusztavvargadr/boxes/windows-10) and [here](https://github.com/gusztavvargadr/packer/). While @Ash258’s version works fine, I use a [slight variant](https://github.com/rasa/scoops/blob/91051f642cd7896cc3d15561d1dd12180fec57a2/Vagrantfile#L22).

2020-12-18 20:01 UTC, dotjairo commented
This https://github.com/alacritty/alacritty/issues/2740 indicates that it's a problem that shows up when you run Alacritty in Remote Desktop sessions and on particular GPU hardware. As such, it's an issue with Alacritty itself, and _not_ a missing dependency, like @Ash258 suggested above. Of note, the installation of Alacritty 0.6.0 (this MR) via scoop worked correctly as demonstrated above by several people. 

Does this provide sufficient rationale for moving forward with this merge request?

2020-12-30 13:05 UTC, equinox commented
@rasa Are you able to give us any info on what needs to be done to get this merged?

2021-01-08 13:38 UTC, earnestma commented
[Alacritty 0.7.0](https://github.com/alacritty/alacritty/releases/tag/v0.7.0) has been released. Should I update this request or maybe start a new one?

As mentioned before, [this will work on real hardware, not virtualized](https://github.com/lukesampson/scoop-extras/pull/5179#issuecomment-748292735), and will install and run fine.

2021-01-16 10:57 UTC, foisonocean commented
Is there anything blocked this PR getting merged?

2021-01-20 14:29 UTC, dotjairo commented
I do believe that the "change requested" is a non-issue, per my [comment above](https://github.com/lukesampson/scoop-extras/pull/5179#issuecomment-748292735). Any way we could get @Ash258 to take another look? Or have another maintainer review this pull request? cc: @rasa

2021-01-20 17:28 UTC, rasa commented
/verify

2021-01-20 17:30 UTC, rasa approved these changes

2021-01-20 17:30 UTC, merged