civo: Add version 0.6.42
lukesampson/scoop-extras pull request #5183
Opened 2020-11-25 10:02 UTC by jaysonsantos

As this is not really that popular I didn't put on main repo, let me know if it should change.

2020-11-25 11:15 UTC, jaysonsantos commented
Hey there @Ash258 could you point out what needs fix?

2020-11-25 17:44 UTC, Ash258 requested changes

2020-11-25 17:44 UTC, Ash258 commented on bucket/civo.json
> +        }
```suggestion
        },
        "hash": {
            "url": "$baseurl/civo-$version-checksums.sha256"
        }
```

2020-11-25 17:44 UTC, Ash258 commented on bucket/civo.json
> +    },
```suggestion
    "bin": "civo.exe",
    "checkver": "github",
```

2020-11-25 17:44 UTC, Ash258 commented on bucket/civo.json
> +    "bin": "civo.exe",
```suggestion
```

2020-11-25 17:44 UTC, Ash258 commented on bucket/civo.json
> +    "description": "Command Line Interface (CLI) for interacting with your Civo resources",
```suggestion
    "description": "CLI library for managing cloud resources such as instances and Kubernetes clusters at Civo.com.",
```

2020-11-25 19:45 UTC, jaysonsantos commented
Should I rebase it or will you squash merge it?

2020-11-27 17:19 UTC, Ash258 commented
/verify

2020-11-27 17:21 UTC, Ash258 approved these changes

2020-11-29 21:14 UTC, merged