Fixing Cura's link
lukesampson/scoop-extras pull request #5232
Opened 2020-12-03 01:28 UTC by MarioGK

Fixes #5231
Close #5231

2020-12-03 01:32 UTC, MarioGK commented
Sorry for the 7bfd05a commit, i messed up my branches already reverted hopefully this will get merged soon

2020-12-03 15:50 UTC, Ash258 requested changes

2020-12-03 15:50 UTC, Ash258 commented on bucket/cura.json
> -    },
Why did you remove this suggest? Where is stated that now the application do not require vcredist?

2020-12-20 20:10 UTC, b-reich commented
@MarioGK can you answer the question?

2020-12-20 20:25 UTC, MarioGK commented
@b-reich Sorry, I was busy and forgot to answer, in the official web site's requirements and on their github, both don't mention any kind of dependency and I tried on a clean windows 10 vm just with scoop and cura installed and it didn't require anything else, that is why I removed

2020-12-20 22:05 UTC, rasa approved these changes

2020-12-20 22:05 UTC, rasa commented
/verify

2020-12-23 08:18 UTC, merged