Update TaskbarX version
lukesampson/scoop-extras pull request #5319
Opened 2020-12-16 22:48 UTC by Lunchb0ne

This also accounts for the split in the architecture of the new versions of the app. The auto-update URL has also been added to account for the different versions.

2020-12-16 22:50 UTC, Lunchb0ne commented
Also, on a side note, is the regex under the checkver needed? I saw the code for the script that does the version checking and seems like it substitutes the regex with another one for getting the latest GitHub release version, if github is specified as the target

2020-12-19 22:34 UTC, Ash258 requested changes

2020-12-19 22:34 UTC, Ash258 commented on bucket/taskbarx.json
>      "homepage": "https://chrisandriessen.nl/web/taskbarx/",
```suggestion
    "homepage": "https://chrisandriessen.nl/taskbarx",
```

2020-12-19 22:34 UTC, Ash258 commented on bucket/taskbarx.json
>          "regex": "TaskbarX_([\\d.]+)\\.zip"
```suggestion
```

2020-12-26 08:20 UTC, Ash258 requested changes

2020-12-26 08:20 UTC, Ash258 commented on bucket/taskbarx.json
>      "bin": "TaskbarX.exe",
I do not think this is good idea.

All configurations are saved into the scheduled task parameter field, so launching it without defined parameters is not desired. Or rather, launching it from any other place than task or configurator does not make sense

```suggestion
```

2020-12-31 15:53 UTC, Ash258 commented
/verify

2020-12-31 15:55 UTC, merged