Create hakuneko.json
lukesampson/scoop-extras pull request #5385
Opened 2020-12-29 15:23 UTC by Witchilich

2020-12-29 23:16 UTC, Ash258 requested changes

2020-12-29 23:22 UTC, Witchilich commented on bucket/hakuneko.json
> +    "license": "Unlicense",
https://github.com/manga-download/hakuneko/blob/master/UNLICENSE

2020-12-31 15:48 UTC, Ash258 commented
/verify

2020-12-31 15:50 UTC, Ash258 approved these changes

2021-01-04 03:51 UTC, merged