jellyfin: Add manifest
lukesampson/scoop-extras pull request #5396
Opened 2020-12-31 04:41 UTC by mertd

Hi,

Jellyfin is a open source fork of Emby, a media server similar to Plex.
This is my first manifest, so I am happy about any feedback I can get.

Also, please squash and merge these changes (if you don't do this anyway) when ready, as my commits are small and many.

2020-12-31 07:41 UTC, Ash258 requested changes
Switch to portable https://github.com/Ash258/Scoop-Ash258/blob/master/bucket/Jellyfin.json

2021-01-02 11:53 UTC, mertd commented
I am not sure I understand what you are requesting exactly. The manifest in this PR is using the same URL (and release of Jellyfin) as the one in your personal bucket. Considering that your manifest is more detailed, I do not mind closing this PR in favour of the manifest in your bucket.

If you are referring to the "more portable" release of Jellyfin than this one, the one that is actually named "portable", I am afraid that it does not contain a runnable jellyfin.exe file and would introduce an additional dependency on the .net core runtime. Would that still be preferrable to this release, considering that the app itself (although not the data) is portable?

2021-01-04 04:12 UTC, Ash258 commented
/verify

2021-01-04 04:13 UTC, Ash258 approved these changes

2021-01-10 20:20 UTC, merged