pencil2d: Add version 0.6.5
lukesampson/scoop-extras pull request #5442
Opened 2021-01-05 16:38 UTC by flavio20002

Add Pencil2d manifest https://www.pencil2d.org/download/

2021-01-05 17:02 UTC, Ash258 requested changes

2021-01-05 17:02 UTC, Ash258 commented on bucket/pencil2d.json
> +    "license": "GPL-2.0-only",
```suggestion
    "license": "GPL-2.0-only",
    "suggest": {
        "vcredist": "extras/vcredist2019"
    },
```

2021-01-06 11:33 UTC, flavio20002 commented
Hi, I accepted all the requests. It is ok now?
Thanks

2021-01-10 08:29 UTC, Ash258 commented
/verify

2021-01-10 08:30 UTC, Ash258 approved these changes

2021-01-10 20:19 UTC, merged