add Picgo with english homepage
lukesampson/scoop-extras pull request #5510
Opened 2021-01-15 09:11 UTC by huangnauh

2021-01-15 09:17 UTC, Ash258 requested changes

2021-01-15 09:17 UTC, Ash258 commented on bucket/picgo.json
> +    "shortcuts": [["PicGo.exe", "PicGo"]],
format with bin/formatjson.ps1

2021-01-15 09:17 UTC, Ash258 commented on bucket/picgo.json
> +    "description": "🚀A simple & beautiful tool for pictures uploading built by vue-cli-electron-builder",
Having emojis in decription is completely absurd.

2021-01-15 09:17 UTC, Ash258 commented on bucket/picgo.json
> +        }
Add hash extraction from $baseurl/latest.yml

2021-01-15 09:17 UTC, Ash258 commented on bucket/picgo.json
> +        "regex": "/PicGo-Setup-([\\w.-]+).exe"
Do not use beta releases

2021-01-15 09:17 UTC, Ash258 commented on bucket/picgo.json
> +    "version": "2.3.0-beta.4",
Update to 2.2.2

2021-01-16 11:12 UTC, huangnauh commented
@Ash258 please take a look

2021-01-16 15:47 UTC, Ash258 requested changes
Next time you will not follow github flow with accepting suggestion via UI all your PRs will be closed.

2021-01-16 15:47 UTC, Ash258 commented on bucket/picgo.json
> +        "regex": "/PicGo-Setup-([\\d.]+).exe"
```suggestion
        "url": "https://github.com/Molunerfinn/PicGo/releases",
        "regex": "/PicGo-Setup-([\\d.]+)\\.exe"
```

2021-01-16 15:47 UTC, Ash258 commented on bucket/picgo.json
> +    "shortcuts": [
https://github.com/Molunerfinn/PicGo/blob/dev/src/main/utils/handleArgv.ts

```suggestion
    "bin": "PicGo.exe",
    "shortcuts": [
```

2021-01-16 15:47 UTC, Ash258 commented on bucket/picgo.json
> +    "description": "A simple & beautiful tool for pictures uploading built by vue-cli-electron-builder",
```suggestion
    "description": "Image uploader/manager",
    "homepage": "https://picgo.github.io/PicGo-Doc/en/",
```

2021-01-18 08:54 UTC, huangnauh commented
> Next time you will not follow github flow with accepting suggestion via UI all your PRs will be closed.

Sorry for the late reply, I received the github suggestion after you reminded me. 
Before that, I only received comments, so I committed the fix via git command instead of ui.

2021-01-20 17:48 UTC, rasa commented
/verify

2021-01-20 17:50 UTC, merged