Add PSKubectlCompletion manifest
lukesampson/scoop-extras pull request #5577
Opened 2021-01-29 04:32 UTC by alexchapar

This can be use to enable kubectl auto-completion for PowerShell

2021-01-30 09:47 UTC, Ash258 requested changes

2021-01-30 09:47 UTC, Ash258 commented on bucket/pskubectlcompletion.json
> +    ],
The notes are pretty much irrelevant

```suggestion
```

2021-01-30 09:47 UTC, Ash258 commented on bucket/pskubectlcompletion.json
> +        "url": "https://psg-prod-eastus.azureedge.net/packages/pskubectlcompletion.$version.nupkg#/dl.7z"
```suggestion
        "url": "https://psg-prod-eastus.azureedge.net/packages/pskubectlcompletion.$version.nupkg"
```

2021-01-30 09:47 UTC, Ash258 commented on bucket/pskubectlcompletion.json
> +    "homepage": "https://github.com/mziyabo/PSKubectlCompletion/",
```suggestion
    "description": "kubectl auto-completion for PowerShell",
    "homepage": "https://github.com/mziyabo/PSKubectlCompletion",
```

2021-01-30 09:47 UTC, Ash258 commented on bucket/pskubectlcompletion.json
> +    "hash": "497d7c0724b5946176d8a6a250e074d1bf3848e9e75adaf2d73d623f57d1716e",
```suggestion
    "hash": "497d7c0724b5946176d8a6a250e074d1bf3848e9e75adaf2d73d623f57d1716e",
    "pre_install": "Remove-Item \"$dir\\_rels\", \"$dir\\package\", \"$dir\\*Content*.xml\" -Recurse",
```

2021-01-30 16:55 UTC, alexchapar commented
Thanks for the comments.. I've applied them

2021-02-04 20:05 UTC, Ash258 commented
/verify

2021-02-04 20:06 UTC, Ash258 approved these changes

2021-02-08 06:26 UTC, merged