matterircd: add version 0.22.0
lukesampson/scoop-extras pull request #5595
Opened 2021-02-01 23:58 UTC by 42wim

2021-02-02 06:04 UTC, Ash258 reviewed
- Add hash extraction from $baseurl/checksums

2021-02-02 06:04 UTC, Ash258 commented on bucket/matterircd.json
> +                "url": "https://github.com/42wim/matterircd/releases/download/v$version/matterircd-$version-windows-32bit.exe"
```suggestion
                "url": "https://github.com/42wim/matterircd/releases/download/v$version/matterircd-$version-windows-32bit.exe#/matterircd.exe"
```

2021-02-02 06:04 UTC, Ash258 commented on bucket/matterircd.json
> +                "url": "https://github.com/42wim/matterircd/releases/download/v$version/matterircd-$version-windows-64bit.exe"
```suggestion
                "url": "https://github.com/42wim/matterircd/releases/download/v$version/matterircd-$version-windows-64bit.exe#/matterircd.exe"
```

2021-02-02 06:04 UTC, Ash258 commented on bucket/matterircd.json
> +    "description": "Connect to your mattermost or slack using your IRC-client of choice.",
```suggestion
    "description": "Connects to mattermost or slack using IRC-client.",
```

2021-02-02 06:04 UTC, Ash258 requested changes
Above

2021-02-02 10:53 UTC, 42wim commented
Thanks, fixes applied

2021-02-04 20:52 UTC, Ash258 requested changes

2021-02-04 20:52 UTC, Ash258 commented on bucket/matterircd.json
> +        }
```suggestion
        },
        "hash": {
            "url": "$baseurl/checksums.txt"
        }
```

2021-02-07 07:15 UTC, Ash258 commented
/verify

2021-02-07 07:16 UTC, Ash258 approved these changes

2021-02-08 06:26 UTC, merged