windowsdesktop-runtime: Update to version 5.0.2
lukesampson/scoop-extras pull request #5637
Opened 2021-02-08 03:36 UTC by x-magic

This manifest will match the latest desktop runtime version. LTS version (3.x) will be added by a separate pull request.

2021-02-10 16:44 UTC, Ash258 commented
/verify obviously autoupdate has to fail

2021-02-11 19:59 UTC, x-magic commented
Seems now fixed.

2021-02-20 21:20 UTC, Ash258 requested changes

2021-02-20 21:20 UTC, Ash258 commented on bucket/windowsdesktop-runtime.json
> +        "url": "https://dotnetcli.azureedge.net/dotnet/Runtime/Current/latest.version",
```suggestion
        "url": "https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/Current/latest.version",
```

2021-02-20 21:20 UTC, Ash258 commented on bucket/windowsdesktop-runtime.json
> +            "hash": "sha512:97f6313f40159086a544f3f52cc1f34a161bd988f12c4f31b2e86eb9ffec0a72d4c9690616d80739c9f8aa65476ab1c7c4a95e804e9333c810f9d2f6d6e7ad2e"
fix URL

2021-02-26 18:51 UTC, Ash258 commented on bucket/windowsdesktop-runtime.json
> +            "hash": "sha512:97f6313f40159086a544f3f52cc1f34a161bd988f12c4f31b2e86eb9ffec0a72d4c9690616d80739c9f8aa65476ab1c7c4a95e804e9333c810f9d2f6d6e7ad2e"
Why do you request review when the URLs are still random instead of the one from autoupdate??

2021-02-26 19:00 UTC, x-magic commented
Version 5.0.3 is out. I'll open a new pull-request.

2021-02-26 19:00 UTC, closed without merging

2021-02-26 19:01 UTC, Ash258 commented
No. Push it to here...

2021-02-26 19:02 UTC, x-magic commented
> No. Push it to here...

Sorry for the trouble... I messed up my fork. Have to recreate one.