nfbc: Add version 1.6.3
lukesampson/scoop-extras pull request #5704
Opened 2021-02-17 05:33 UTC by r0uv3n

Hi, first contribution. Hope full name in description and no autoupdate on the hash are the right ways to do things (hash has to be generated from downloaded file). This uses Expand-DarkArchive as done for example in the [portable vcreddist 2013 manifest](https://github.com/lukesampson/scoop-extras/blob/a8bcb1b43b0230a9348a422017be31fe625cea70/bucket/vcredist2013-portable.json)).

2021-02-17 06:07 UTC, Ash258 requested changes
./bin/checkver.ps1 nbfc -f

2021-02-17 06:07 UTC, Ash258 commented on bucket/nbfc.json
> +  },
license: GPL-3.0-only

2021-02-17 06:07 UTC, Ash258 commented on bucket/nbfc.json
> +  "url": "https://github.com/hirschmann/nbfc/releases/download/1.6.3/NoteBookFanControl.1.6.3.setup.exe#/setup.exe",
renaming exe to exe does not make sense

2021-02-17 06:07 UTC, Ash258 commented on bucket/nbfc.json
> +    "Get-ChildItem \"$dir\\setup.exe\" | ForEach-Object { Expand-DarkArchive $_ \"$dir\\nbfc\" -Removal }",
$fname

2021-02-17 20:01 UTC, r0uv3n commented
I just noticed I forgot to register the nbfc service, this pull request is definetely incomplete, will be working on this.

2021-02-19 23:03 UTC, r0uv3n commented
It seems I'm in over my head here, so I should probably close this.

2021-02-19 23:03 UTC, closed without merging