Adds Librewolf
lukesampson/scoop-extras pull request #5785
Opened 2021-03-03 02:50 UTC by 1hiking

In a similar fashion from Chromium to Ungoogled-chromium, [LibreWolf ](https://librewolf-community.gitlab.io/)is a browser with the goals of privacy and with no telemetry included from Mozilla.

P.S: This is my first scoop, happy to contribute to the project!

2021-03-03 16:31 UTC, 1hiking commented
I would use the `checkver` tool, but I am bad at RegEx :/, the only example I found which uses GitLab is `cmake-rc`

2021-03-03 17:45 UTC, Ash258 requested changes
Implementing autoupdate is waste of time since Gitlab release asset api is ...

I do not like these random forks in Extras. Unsubscribing.

2021-03-03 17:45 UTC, Ash258 commented on bucket/librewolf.json
> +    ]
```suggestion
    ],
    "checkver": {
        "url": "https://gitlab.com/api/v4/projects/13852981/repository/tags",
        "jsonpath": "$[0].name",
        "regex": "v([\\w.-]+)"
    }
```

2021-03-03 17:45 UTC, Ash258 commented on bucket/librewolf.json
> +        "hash": "EA14B2138553E6FB1DA3C0C1D81972924F7584214A9695D0DC50B70901805B0C"
```suggestion
            "url": "https://gitlab.com/librewolf-community/browser/windows/uploads/b6b3189fc1c0042ff0503e8b2546b00d/librewolf-86.0.en-US.win64.zip",
            "hash": "ea14b2138553e6fb1da3c0c1d81972924f7584214a9695d0dc50b70901805b0c"
```

2021-03-27 23:36 UTC, recipe12 commented
LibreWolf is now version 87.0

2021-08-13 01:10 UTC, 1hiking commented
I'm closing this as it's not longer up-to date. However anyone is free to use my json file.

2021-08-13 01:10 UTC, closed without merging