rpi-imager: Add version 1.5
lukesampson/scoop-extras pull request #5816
Opened 2021-03-09 02:51 UTC by alexchapar

Tool for writing an Raspberry Pi OS images to SD cards

2021-03-09 17:21 UTC, Ash258 requested changes
`git mv bucket/rpi-imager.json bucket/raspbery-pi-imager.json`

2021-03-09 17:21 UTC, Ash258 commented on bucket/rpi-imager.json
> +    },
```suggestion
    "license": "Apache-2.0",
```

![image](https://user-images.githubusercontent.com/13260377/110510058-19a41200-8103-11eb-8841-60f2d4964b6f.png)

2021-03-09 17:21 UTC, Ash258 commented on bucket/rpi-imager.json
> +    "bin": "rpi-imager.exe",
```suggestion
```

2021-03-09 17:21 UTC, Ash258 commented on bucket/rpi-imager.json
> +    "homepage": "https://github.com/raspberrypi/rpi-imager",
```suggestion
    "homepage": "https://www.raspberrypi.org/software",
```

2021-03-09 17:21 UTC, Ash258 commented on bucket/rpi-imager.json
> +    },
```suggestion
    "checkver": "imager_([\\d.]+)\\.exe",
```

2021-03-09 17:21 UTC, Ash258 commented on bucket/rpi-imager.json
> +        "url": "https://github.com/raspberrypi/rpi-imager/releases/download/v$version/imager-$version.exe"
```suggestion
        "url": "https://github.com/raspberrypi/rpi-imager/releases/download/v$version/imager-$version.exe#/dl.7z"
```

2021-03-09 17:21 UTC, Ash258 commented on bucket/rpi-imager.json
> +    "hash": "sha256:9c62170a4180d64dfffc6f2af4bc5f3dc04cafd99c2511ed3af38dad9e2173e2",
```suggestion
    "hash": "9c62170a4180d64dfffc6f2af4bc5f3dc04cafd99c2511ed3af38dad9e2173e2",
```

2021-03-09 17:21 UTC, Ash258 commented on bucket/rpi-imager.json
> +    "post_install": "Remove-Item \"$dir\\`$PLUGINSDIR\", \"$dir\\Uninst*\" -Force -Recurse",
```suggestion
    "pre_install": "Remove-Item \"$dir\\`$*\", \"$dir\\uninst*\" -Recurse",
```

2021-03-09 17:49 UTC, alexchapar commented
Thanks for your comments. I applied them and rename the file as proposed.

2021-03-12 20:55 UTC, Ash258 commented
/verify

2021-03-12 20:56 UTC, Ash258 approved these changes

2021-03-14 20:22 UTC, merged