Update insomnia.json
lukesampson/scoop-extras pull request #5847
Opened 2021-03-11 11:04 UTC by lucasiro

version 2021.1.1

2021-03-11 11:07 UTC, Ash258 commented
/verify Checkver has to fail

Insomnia and insomnia designer were merged together. Freeze insonmnia-designer manifest with notes about this change

2021-03-11 12:47 UTC, lucasiro commented
insonmnia-designer manifest freezed with note an suggest

2021-03-12 20:38 UTC, Ash258 requested changes
- Fix checkver for insomnia.json
    - Run `checkver insomnia -f` after
- Remove checkver and autoupdate from designer

2021-03-12 20:38 UTC, Ash258 commented on bucket/insomnia-designer.json
> +    },
```suggestion
    "notes": "Insomnia Designer and Insomnia Core were merged together. Install 'insomnia' instead.",
```

2021-03-18 01:08 UTC, Ash258 commented
/verify

2021-03-18 01:10 UTC, merged