Create logseq.json for Logseq
lukesampson/scoop-extras pull request #5951
Opened 2021-04-01 01:35 UTC by HueLiu

Logseq is a privacy-first, open-source(frontend now, backend later) platform for knowledge sharing and management.

Here you go: https://github.com/logseq/logseq

2021-04-01 01:39 UTC, Ash258 requested changes

2021-04-01 01:39 UTC, Ash258 commented on bucket/logseq.json
> +        "identifier": "GNU Affero General Public License v3.0",
Invalid SPDX identifier

2021-04-01 01:39 UTC, Ash258 commented on bucket/logseq.json
> +    "notes": "We don't persist your Logseq data, they are still storaged in \"%APPDATA%\\Logseq\".",
Not needed message

```suggestion
```

2021-04-01 01:39 UTC, Ash258 commented on bucket/logseq.json
> +    "description": "Logseq is a privacy-first, open-source(frontend now, backend later) platform for knowledge sharing and management.",
Mentioning application name and that it is open source, is redundant

2021-04-01 01:39 UTC, Ash258 commented on bucket/logseq.json
> +    "post_install": "Remove-Item \"$dir\\lib\",\"$dir\\_rels\" -Recurse -Force",
Nonse to have special install block for removing files

2021-04-01 01:39 UTC, Ash258 commented on bucket/logseq.json
> +    "installer": {
Convert to pre_install

2021-04-01 01:39 UTC, Ash258 commented on bucket/logseq.json
> +            "Expand-7ZipArchive \"$nupkg\" \"$dir\" -Removal",
Expand archive accept wildcard

2021-04-01 01:39 UTC, Ash258 commented on bucket/logseq.json
> +            "$dotnet = (Get-ChildItem \"$dir\\lib\" 'net*' | Select-Object -First 1).FullName",
Variable is not needed

2021-04-01 11:47 UTC, HueLiu commented
Hi,

Since I am new to scoop, there are many mistakes. Thank you very much for your review and suggestions.

I've updated some of the code, I wasn't sure if it was appropriate, thanks!

2021-04-02 03:35 UTC, Ash258 requested changes

2021-04-02 03:35 UTC, Ash258 commented on bucket/logseq.json
> +    "description": "A privacy-first platform for knowledge sharing and management.",
```suggestion
    "description": "A privacy-first platform for knowledge sharing and management",
```

2021-04-02 03:35 UTC, Ash258 commented on bucket/logseq.json
> +    "homepage": "https://logseq.com/",
```suggestion
    "homepage": "https://logseq.com",
```

2021-04-02 03:35 UTC, Ash258 commented on bucket/logseq.json
> +    },
```suggestion
    "license": "AGPL-3.0-only",
```

2021-04-02 03:35 UTC, Ash258 commented on bucket/logseq.json
> +        "url": "https://github.com/logseq/logseq/releases/download/$version/logseq-win-x64-$version.exe#/dl.7z"
```suggestion
        "architecture": {
            "64bit": {
                "url": "https://github.com/logseq/logseq/releases/download/$version/logseq-win-x64-$version.exe#/dl.7z"
            }
        }
```

2021-04-02 03:35 UTC, Ash258 commented on bucket/logseq.json
> +    "version": "0.0.16",
```suggestion
    "version": "0.0.17",
```

2021-04-02 03:35 UTC, Ash258 commented on bucket/logseq.json
> +    "hash": "bf1dc4e7b8219724926b77fd8b4cfdb3a1483ac0a3120020d7297096881e88be",
```suggestion
    "architecture": {
        "64bit": {
            "url": "https://github.com/logseq/logseq/releases/download/0.0.17/logseq-win-x64-0.0.17.exe#/dl.7z",
            "hash": "12d342d26d46ed4ebe97891a2798e482ab0161d79def27395cab654062966ee0"
        }
    },
```

2021-04-02 03:35 UTC, Ash258 commented on bucket/logseq.json
> +            "Remove-Item \"$dir\\*.gif\", \"$dir\\_rels\" , \"$dir\\lib\", \"$dir\\package\", \"$dir\\*.xml\"  -Recurse"
```suggestion
        "Expand-7ZipArchive \"$dir\\logseq-*-full.nupkg\" -ExtractDir 'lib\\net45' -Removal",
        "Remove-Item \"$dir\\lib\", \"$dir\\Update*\" -Recurse"
```

2021-04-05 01:27 UTC, Ash258 requested changes
https://github.com/lukesampson/scoop-extras/pull/5951#discussion_r606054476

2021-04-09 16:01 UTC, Ash258 commented
/verify

2021-04-09 16:02 UTC, Ash258 approved these changes

2021-04-12 11:48 UTC, merged