fat32format-gui: Add version 1.01
lukesampson/scoop-extras pull request #5997
Opened 2021-04-09 02:17 UTC by kriswilk

2021-04-09 03:46 UTC, Ash258 requested changes
`git mv bucket/fat32format-gui bucket/fat32format-gui.json`

2021-04-09 03:46 UTC, Ash258 commented on bucket/fat32format-gui
> +            "fat32format-gui"
```suggestion
            "FAT32 Format"
```

2021-04-09 03:46 UTC, Ash258 commented on bucket/fat32format-gui
> +    "bin": "guiformat.exe",
```suggestion
```

2021-04-09 04:50 UTC, kriswilk commented
> `git mv bucket/fat32format-gui bucket/fat32format-gui.json`

Sorry. 🤦‍♂️

Thanks for the other suggestions. Still new to scoop and didn't know that "bin" could be omitted in this case.

2021-04-09 13:36 UTC, kriswilk commented
On second thought, I re-added the shim for "guiformat.exe" since it's still nice to be able to launch the tool from the command line.

2021-04-09 13:37 UTC, Ash258 commented
No it is not. If there are no command line arguments available it does not make sense to add it.

2021-04-09 13:40 UTC, kriswilk commented
> No it is not. If there are no command line arguments available it does not make sense to add it.

OK, fair enough. I've removed it. But I have launched it more than a few times from my terminal that way.

2021-04-09 17:16 UTC, Ash258 requested changes

2021-04-09 17:16 UTC, Ash258 commented on bucket/fat32format-gui.json
> +    "hash": "647fb4f5108af632c3d52fec34934922c50c70585697504e92fb80b3b7d05ee3",
```suggestion
    "homepage": "http://ridgecrop.co.uk",
    "license": "Unknown",
    "architecture": {
        "64bit": {
            "url": "http://ridgecrop.co.uk/guiformat-x64.Exe#/guiformat.exe",
            "hash": "13d045f582d559c830f2e30f835ac56803844825fe6152d2d5f78367b19edb9a"
        },
        "32bit": {
            "url": "http://ridgecrop.co.uk/guiformat.exe",
            "hash": "647fb4f5108af632c3d52fec34934922c50c70585697504e92fb80b3b7d05ee3"
        }
    },
```

2021-04-09 17:46 UTC, kriswilk commented
Thought of adding the 64-bit version but was hesitant since the app author states:

> There is an x64 build of Guiformat here. However the x86 build works fine on both x86 and x64 and you should use that.

No idea why that recommendation was made but I was trying to respect it. Personally, I agree it makes sense to offer both.

2021-04-11 09:40 UTC, Ash258 commented
/verify

2021-04-11 09:42 UTC, Ash258 approved these changes

2021-04-12 11:48 UTC, merged