dax-studio: Add installer
lukesampson/scoop-extras pull request #6069
Opened 2021-04-20 18:58 UTC by adrianocorrea

2021-04-24 08:27 UTC, Ash258 requested changes

2021-04-24 08:27 UTC, Ash258 commented on bucket/dax-studio.json
> +    ],
```suggestion
    "pre_install": "if (!(Test-Path \"$persist_dir\\settings.json\")) { Set-Content \"$dir\\settings.json\" '{}' -Encoding ascii }",
    "shortcuts": [
        [
            "DaxStudio.exe",
            "DAX Studio"
        ],
        [
            "DaxStudio.Checker.exe",
            "DAX Studio Checker"
        ]
    ],
    "persist": [
        "AutoSaveFiles",
        "Log",
        "QueryHistory",
        "settings.json"
    ],
```

2021-04-24 08:27 UTC, Ash258 commented on bucket/dax-studio.json
> +    },
```suggestion
    "homepage": "https://daxstudio.org",
    "license": "MS-RL",
    "url": "https://github.com/DaxStudio/DaxStudio/releases/download/v2.15.0/DaxStudio_2_15_0_portable.zip",
    "hash": "c6ddd183a095b745c308f83a31081a7d5996f7914684b1028c41ddaa7e45b10a",
```

2021-04-24 08:27 UTC, Ash258 commented on bucket/dax-studio.json
> +        }
```suggestion
        "url": "https://github.com/DaxStudio/DaxStudio/releases/download/v$version/DaxStudio_$underscoreVersion_portable.zip"
```

2021-05-04 12:28 UTC, adrianocorrea commented on bucket/dax-studio.json
> +        }
Done.

2021-05-04 12:36 UTC, adrianocorrea reviewed
Updated formulae.

2021-05-04 19:10 UTC, Ash258 requested changes
Always create `bin\.portable` and `.portable` files

https://github.com/DaxStudio/DaxStudio/blob/87f11b343a2e85a24311879d5fe96a090ba55170/src/DaxStudio.Checker/Checker.cs#L713-L718

2021-05-04 20:03 UTC, adrianocorrea commented
Sorry, I am not quite sure what is the outstanding issue here. The checker you have highlighted checks if there is a `.portable` file in the bin folder OR in the current folder. The installer is creating the required `.portable` file in the bin folder during the extraction (see folder `.\scoop\apps\dax-studio\current\bin`), which allows the software to work as expected. 

Did I miss something?

2021-06-06 15:58 UTC, closed without merging