Add gdu
lukesampson/scoop-extras pull request #6098
Opened 2021-04-25 10:53 UTC by telenieko

[gdu](https://github.com/dundee/gdu) is a disk usage analyzer with console interface written in Go.

This of it as a visual `du` or console based [`windirstat`](https://windirstat.net/) ([already in scoop](https://github.com/lukesampson/scoop-extras/blob/master/bucket/windirstat.json))

Regarding [the criteria for inclussion in the main bucket](https://github.com/lukesampson/scoop/wiki/Criteria-for-including-apps-in-the-main-bucket):

- I do not think this is a reasonably well-know and/or widely used developer tool. The project is relatively new.
- the manifest points to the latest version and includes autoupdate
- it is the full version (open source project)
- install is fairly standard (unzip)
- it is not a GUI tool

Hence, because the first criteria is not met, this is proposed for inclusion in extras.

marc

2021-04-25 12:24 UTC, Ash258 requested changes

2021-04-25 12:24 UTC, Ash258 commented on bucket/gdu.json
> +            "mode": "download"
Add hash extraction from sha256sums.txt

```suggestion
```

2021-04-25 12:24 UTC, Ash258 commented on bucket/gdu.json
> +    },
```suggestion
```

2021-04-25 12:24 UTC, Ash258 commented on bucket/gdu.json
> +    "description": "Disk usage analyzer with console interface written in Go",
Language is completely irrelevant for end user
```suggestion
    "description": "Disk usage analyzer with console interface",
```

2021-04-25 12:24 UTC, Ash258 commented on bucket/gdu.json
> +    },
```suggestion
            "hash": "235289e39cc2574c277520a9aef09cbba9474d8847114f61706f1b252b80c770",
            "bin": [
                [
                    "gdu_windows_amd64.exe",
                    "gdu"
                ]
            ]
        }
    },
    "checkver": "github",
```

2021-04-26 14:18 UTC, telenieko commented
@Ash258 I added the hash download, though I'm not sure I did right,
the [https://scoop-docs.vercel.app/docs/concepts/App-Manifest-Autoupdate.html#adding-autoupdate-to-a-manifest](docs) show examples with the `.txt` and `.txt.asc` files but as far as I know the hashes themselves are only on the `.txt` file.

So that's what I did. Checking againts the `.txt` file on the release.

2021-05-04 18:56 UTC, Ash258 commented
/verify

2021-05-04 19:05 UTC, Ash258 commented
Not working properly. Everytime command end with:

```
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [select]:
github.com/rivo/tview.(*Application).Run(0xc00006e000, 0x0, 0x0)
        /home/dundee/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210217110421-8a8f78a6dd01/application.go:302 +0x1d8
github.com/dundee/gdu/v4/tui.(*UI).StartUILoop(0xc000024270, 0xc6ad78, 0xc000024270)
        /home/dundee/go/src/github.com/dundee/gdu/tui/tui.go:145 +0x3b
github.com/dundee/gdu/v4/cmd/app.(*App).Run(0xc0000d1d20, 0x0, 0x0)
        /home/dundee/go/src/github.com/dundee/gdu/cmd/app/app.go:104 +0x2e9
github.com/dundee/gdu/v4/cmd.runE(0xdcd260, 0xe14870, 0x0, 0x0, 0x0, 0x0)
        /home/dundee/go/src/github.com/dundee/gdu/cmd/root.go:85 +0x1dd
github.com/spf13/cobra.(*Command).execute(0xdcd260, 0xc000084200, 0x0, 0x0, 0xdcd260, 0xc000084200)
        /home/dundee/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xdcd260, 0x98b001, 0x0, 0x0)
        /home/dundee/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/dundee/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/dundee/gdu/v4/cmd.Execute()
        /home/dundee/go/src/github.com/dundee/gdu/cmd/root.go:91 +0x34
main.main()
        /home/dundee/go/src/github.com/dundee/gdu/main.go:8 +0x27

goroutine 83 [select]:
github.com/gdamore/tcell/v2.(*cScreen).PollEvent(0xc00005a000, 0xc000163fa0, 0xc0002588e0)
        /home/dundee/go/pkg/mod/github.com/gdamore/tcell/v2@v2.2.0/console_win.go:372 +0x89
github.com/rivo/tview.(*Application).Run.func2(0xc000161ca0, 0xc00006e000)
        /home/dundee/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210217110421-8a8f78a6dd01/application.go:267 +0xa9
created by github.com/rivo/tview.(*Application).Run
        /home/dundee/go/pkg/mod/github.com/rivo/tview@v0.0.0-20210217110421-8a8f78a6dd01/application.go:254 +0x11d
```

2021-05-05 06:26 UTC, telenieko commented
> Not working properly. Everytime command end with:

Hi,

You added s commit changing the hash url to $baseurl but I do not see to what value is the baseurl defined.

But it looks to me like now the url to the hash file is not appropriately defined.

Please verify without that commit (ie, with the previously defined hash url)

Thanks, 
marc

2021-05-05 06:39 UTC, Ash258 commented
What is the point of your comment??

Do you try to suggest that the hash extraction, while autoupdate is causing gdu executable to be malfunctioning and panicking in, go trace?

Or just pinpoint your lack of knowledge how scoop works, inability to search for logs, test it yourself or see other manifests which uses it?

...

https://github.com/lukesampson/scoop-extras/runs/2503362450?check_suite_focus=true#step:4:141

2021-05-05 10:18 UTC, telenieko commented
> What is the point of your comment??
> Do you try to suggest that the hash extraction, while autoupdate is causing gdu executable to be malfunctioning and panicking in, go trace?
> Or just pinpoint your lack of knowledge how scoop works, inability to search for logs, test it yourself or see other manifests which uses it?

My lack of knowledge is not in question. I can attest that I have less than basic powershell knowledge and very basic golang knowledge. Until now I thought that to contribute manifest files it was enough to be able to write a properly formatted JSON file and test it locally.

Regarding the last part of your comment "inability to search for logs, test it yourself or see other manifests which uses it?":

Up to now, the three manifest files I've submited have consisted on:

- Find a similar manifest to use as a base (ie: if it is electron app find an electron app like krita to start from)
- Cleanup what is not needed, adapt urls, versions and hashes
- put a wrong version in place to run `checkver` and see that autoupdate works and gets the hashes
- do a `scoop install .\my_manifest.json`
- test app
- uninstall, install again
- rinse & repeat if there's a new release

To be honest, I do believe this to be a decent workflow for non-programmers to contribute manifest files. Of course, I've only submitted three very basic manifests.

Regarding my previous comment, given my limited knowledge of both systems (scoop & golang) my point was merely to state I did not understand where `$baseurl` was comming from or if there was a relationship between the error or the change. Now I see it does not.

Moving on to the problem at hand. The trace you posted looks like a problem in gdu itself, not in scoop or the proposed manifest file. That would explain the `waiting-upstream` tag you added. Though I could not find the upstream issue to wait for?.

Now, if it is so that the bug is in gdu and the manifest is Ok (?): the question would be wether a manifest has to be held off because there is a bug that affects some people even if the manifest is Ok. That meaning: is it expected for the "packager" to hold for all possibly blocking bugs of an application before it can make its way into the repository?

Coming back to "inability to search for logs, test it yourself or see other manifests which uses it?", if this is an upstream issue that comment would be out of place and out of tone.

If my previous comment could be interpreted in any negative way please accept my apologies.

Lastly, if my proposed manifest file can be improved in anyway please let me know.

2021-08-13 11:26 UTC, telenieko commented
@Ash258 I just updated the manifest to the latest gdu version.

Please let me know what else needs fixing from this point.

Thx,
Marc

2021-09-29 19:05 UTC, Ash258 commented
https://github.com/ScoopInstaller/Main/blob/master/bucket/gdu.json

2021-09-29 19:05 UTC, closed without merging