Add Livesplit version 1.8.16
lukesampson/scoop-extras pull request #6392
Opened 2021-06-27 18:11 UTC by Vngdv

2021-06-27 18:23 UTC, Ash258 requested changes
Investigate all required files/folders for persisting

https://livesplit.org/downloads/

2021-06-27 18:23 UTC, Ash258 commented on bucket/livesplit.json
> +    "homepage": "https://livesplit.org/",
```suggestion
    "description": "Timer for speedrunners",
    "homepage": "https://livesplit.org",
```

2021-06-27 18:23 UTC, Ash258 commented on bucket/livesplit.json
> +    "bin": "LiveSplit.exe",
```suggestion
    "bin": "LiveSplit.exe",
    "shortcuts": [
        [
            "LiveSplit.exe",
            "LiveSplit"
        ]
    ],
```

2021-07-03 12:58 UTC, Ash258 commented
Why do you request review when you did not do all the required actions??

![image](https://user-images.githubusercontent.com/13260377/124354990-31058e80-dc0f-11eb-96ff-8dbc3d24af2e.png)

2021-07-03 13:25 UTC, Vngdv commented
Oh sorry. I didn't quite understand what you meant. I am going to fix it ASAP!

2021-07-03 14:10 UTC, Vngdv commented
So it seems like LiveSplit saves data into "settings.cfg" and "LiveSplit.AutoSplitters.xml" files. They are both contained in the main application folder. I tried to add them like this: `"persist": [ "settings.cfg", "LiveSplit.AutoSplitters.xml" ],`. But this only seemed to work on folders. Did I do something wrong or is there another way to save files?

2021-10-02 16:37 UTC, closed without merging