actionlint: add actionlint bucket. version 1.5.2
lukesampson/scoop-extras pull request #6549
Opened 2021-08-02 13:44 UTC by guitarrapc

:octocat: Static checker for GitHub Actions workflow files.

It is useful for every GitHub Actions users and work well on Windows, too.

2021-08-02 14:00 UTC, Ash258 requested changes

2021-08-02 14:00 UTC, Ash258 commented on bucket/actionlint.json
> +    "url": "https://github.com/rhysd/actionlint/releases/download/v1.5.2/actionlint_1.5.2_windows_amd64.zip",
Add 32bit version

2021-08-02 14:00 UTC, Ash258 commented on bucket/actionlint.json
> +        "url": "https://github.com/rhysd/actionlint/releases/download/v$version/actionlint_$version_windows_amd64.zip"
Add 32bit version

2021-08-02 14:29 UTC, guitarrapc commented on bucket/actionlint.json
> +    "url": "https://github.com/rhysd/actionlint/releases/download/v1.5.2/actionlint_1.5.2_windows_amd64.zip",
added 32bit

2021-08-02 14:29 UTC, guitarrapc commented on bucket/actionlint.json
> +        "url": "https://github.com/rhysd/actionlint/releases/download/v$version/actionlint_$version_windows_amd64.zip"
added 32bit

2021-08-02 14:29 UTC, guitarrapc commented on bucket/actionlint.json
> +        "url": "https://github.com/rhysd/actionlint/releases/download/v$version/actionlint_$version_windows_amd64.zip"
done.

2021-08-02 14:29 UTC, guitarrapc commented on bucket/actionlint.json
> +    "description": ":octocat: Static checker for GitHub Actions workflow files",
done

2021-08-02 14:29 UTC, guitarrapc commented on bucket/actionlint.json
> +    "url": "https://github.com/rhysd/actionlint/releases/download/v1.5.2/actionlint_1.5.2_windows_amd64.zip",
done

2021-08-02 14:29 UTC, guitarrapc commented on bucket/actionlint.json
> +        "url": "https://github.com/rhysd/actionlint/releases/download/v$version/actionlint_$version_windows_amd64.zip"
done

2021-08-02 14:30 UTC, guitarrapc commented
confirm auto updater successfully detect new version.
https://github.com/guitarrapc/scoop-bucket/commit/46ec68b8156ab157aca3f1d2e43d189303629f54

2021-08-06 20:29 UTC, Ash258 requested changes

2021-08-06 20:29 UTC, Ash258 commented on bucket/actionlint.json
> +    "license": "MIT",
```suggestion
    "version": "1.5.2",
    "description": "Static checker for GitHub Actions workflow files",
    "homepage": "https://github.com/rhysd/actionlint",
    "license": "MIT",
```

2021-08-06 20:29 UTC, Ash258 commented on bucket/actionlint.json
> +                }
```suggestion
                "url": "https://github.com/rhysd/actionlint/releases/download/v$version/actionlint_$version_windows_386.zip"
```

2021-08-06 20:29 UTC, Ash258 commented on bucket/actionlint.json
> +                }
```suggestion
                "url": "https://github.com/rhysd/actionlint/releases/download/v$version/actionlint_$version_windows_386.zip"
```

2021-08-06 20:29 UTC, Ash258 commented on bucket/actionlint.json
> +        }
```suggestion
        },
        "hash": {
            "url": "$baseurl/actionlint_$version_checksums.txt"
        }
```

2021-08-07 02:31 UTC, guitarrapc commented on bucket/actionlint.json
> +                }
windows_386? just remove trailing `,`?

2021-08-07 02:36 UTC, guitarrapc commented on bucket/actionlint.json
> +                }
done

2021-08-07 02:37 UTC, guitarrapc commented
@Ash258 Thank you for the review, all fixes commited.

2021-08-08 13:44 UTC, Ash258 commented
/verify

2021-08-08 13:46 UTC, Ash258 approved these changes

2021-08-22 19:44 UTC, merged