audacity: Update to 3.0.3
lukesampson/scoop-extras pull request #6567
Opened 2021-08-05 13:26 UTC by petlyh

Update audacity to version 3.0.3 and add autoupdate

2021-08-05 22:03 UTC, cybernoid23 commented
If I am not mistaken, there is a slight error in the checkver regex. Shouldn't it be `"[Aa]udacity-win-([\\d.]+)-64bit\\.zip"`
 instead of `"[Aa]udacity-win-([\\d.]+)-64bit\\.zip\""` ?

2021-08-06 06:54 UTC, petlyh commented
The escaped quotation mark does seem to be unnecessary.

This is the HTML that the regex looks for:
`<A HREF="audacity-win-3.0.3-64bit.zip"><IMG SRC="/dl.gif" class="dl" TITLE="[Download]" ALT=""></A></TD><TD> <A HREF="audacity-win-3.0.3-64bit.zip/" TITLE="Downloads, contents, member browsing &amp; more ..."><B>audacity-win-3.0.3-64bit.zip</B></A>`

With the current regex, only the first instance of the filename is matched.
By removing the quotation mark, all three instances will be matched.
However, as scoop uses the first match in the case of multiple matches
(unless reverse is used), the result seems to be the same either way.

I am not sure if it should be changed. Any thoughts?

2021-08-06 20:54 UTC, Ash258 requested changes

2021-08-06 20:54 UTC, Ash258 commented on bucket/audacity.json
> +    ],
```suggestion
    "bin": "Audacity.exe",
```

2021-08-06 20:54 UTC, Ash258 commented on bucket/audacity.json
> +        "regex": "[Aa]udacity-win-([\\d.]+)-64bit\\.zip\""
Not needed change

```suggestion
        "regex": "[Aa]udacity-win-([\\d.]+)-32bit\\.zip\""
```

2021-08-08 14:33 UTC, Ash258 commented
/verify

2021-08-08 14:37 UTC, merged