Added tageditor version 3.4.2
lukesampson/scoop-extras pull request #6632
Opened 2021-08-15 12:11 UTC by KaranKad

Added new application

2021-08-15 12:15 UTC, Ash258 requested changes
Why there are no msvc builds??

2021-08-15 12:15 UTC, Ash258 commented on bucket/tageditor.json
> +            "tageditor-3.4.2-x86_64-w64-mingw32.exe",
Having versioned executable in shortcuts in manifest, which has autoupdate is really not good idea...

2021-08-15 12:15 UTC, Ash258 commented on bucket/tageditor.json
> +        }
Where is 32bit veersion??

2021-08-15 12:15 UTC, Ash258 commented on bucket/tageditor.json
> +    "shortcuts": [
https://github.com/Martchus/tageditor#cli

2021-08-15 12:15 UTC, Ash258 commented on bucket/tageditor.json
> +    },
```suggestion
    "checkver": "githbu",
```

2021-08-15 12:15 UTC, Ash258 commented on bucket/tageditor.json
> +            }
32bit version...

2021-08-15 12:59 UTC, Ash258 requested changes

2021-08-15 12:59 UTC, Ash258 commented on bucket/tageditor.json
> +    "pre_install": "Get-ChildItem \"$dir\\tageditor*.exe\" | Rename-Item -NewName \"$dir\\tageditor.exe\"",
- Gci is overkill. Explicitly pass the executable name to -Path
- Rename item does not take full path

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/rename-item?view=powershell-7.1#description

2021-08-15 13:12 UTC, Ash258 requested changes

2021-08-15 13:12 UTC, Ash258 commented on bucket/tageditor.json
> +    "pre_install": "Rename-Item $dir\\tageditor*.exe $dir\\tageditor.exe",
- Why did you remove the quotes?
- Rename-Item does not take wildcard
- Rename-Item does not take fullpath for -NewName

2021-08-15 14:13 UTC, KaranKad commented
Any reason why `"pre_install": "Get-ChildItem \"$dir\\tageditor*.exe\" | Rename-Item -NewName \"$dir\\tageditor.exe\"",` won't do. 
I tried to find closest application that matches this applications condition's and I found [Godot](https://github.com/lukesampson/scoop-extras/blob/master/bucket/godot.json)

- Portable.
- Single binary directly inside .zip file without additional directories.
- Binary named with version.

Everything matches except download location, so I decided to see its `pre_install` script and adapt it to this application and it works just like Godot's, and successfully installs. I don't know too much about PowerShell scripting or how scoop handles stuff so please show correct changes by correcting my PR.

2021-08-16 07:38 UTC, Ash258 commented
/verify

2021-08-16 07:40 UTC, Ash258 approved these changes

2021-08-22 19:43 UTC, merged