Added picocrypt json
lukesampson/scoop-extras pull request #6823
Opened 2021-09-09 14:04 UTC by Duckle29

Picocrypt is a tiny tool for encrypting files

2021-09-09 14:37 UTC, Ash258 requested changes

2021-09-09 14:37 UTC, Ash258 commented on bucket/picocrypt.json
> +    "homepage": "https://evansu.cc/picocrypt",
Absolutely useless homepage....

![image](https://user-images.githubusercontent.com/13260377/132705960-735f46ea-721c-4ca7-b3ab-f09f30d85fd1.png)

2021-09-09 14:37 UTC, Ash258 commented on bucket/picocrypt.json
> +    "description": "A very small, very simple, yet very secure encryption tool",
Does not tell end user enything. What does it encrypt?? What is it for?

2021-09-09 14:37 UTC, Ash258 commented on bucket/picocrypt.json
> +    "bin": "Picocrypt.exe",
What are command line options?

2021-09-10 17:44 UTC, Duckle29 commented
I am no longer using this tool

2021-09-10 17:44 UTC, closed without merging